version: "2"
plugins:
  fixme:
    enabled: true
  sonar-java: 
    enabled: true
    config:
      minimum_severity: major
  git.legal:
    enabled: true
  markdown:
    enabled: true
  checkstyle:
    enabled: true
  pmd:
    enabled: true
exclude_patterns:
  - ".gitlab/"
  - ".gradle/"
  - ".settings/"
  - ".vscode/"
  - "bin/"
  - "build/"
  - "gradle/"
  - "lib/"
  - "src/test/"
checks:
  method-lines:
    config:
      threshold: 35
  method-complexity:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 500